"""Contribution analysis, including regressions for four bugs found by running
an earlier deterministic engine against a fixture with a known answer.

The fixture is generated by scripts/make_demo_data.py, which prints the ground
truth it was built around. Numbers asserted here come from that.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from analyst.analysis import analyze_change, coerce_numeric, normalize_categorical
from analyst.analysis.change import Breakdown, Slice, _slices

FIXTURE = "data/sales_2026.csv"


@pytest.fixture(scope="module")
def sales() -> pd.DataFrame:
    df = pd.read_csv(FIXTURE)
    df["revenue"] = coerce_numeric(df["revenue"])
    df["order_date"] = pd.to_datetime(df["order_date"], format="%m/%d/%Y")
    return df.drop_duplicates()


@pytest.fixture(scope="module")
def march(sales):
    return analyze_change(
        sales, metric="revenue", date_column="order_date", period_after="2026-03"
    )


# --------------------------------------------------------------- ground truth


def test_reproduces_the_known_total_change(march):
    assert march.delta == pytest.approx(-465_306.31, abs=0.01)
    assert march.pct_change == pytest.approx(-16.11, abs=0.05)


def test_finds_the_true_dominant_contributor(march):
    """West x Laptop is the answer; -11.08pp of a -16.1pp move."""
    top = march.intersection.slices[0]
    assert set(top.segment.split(" x ")) == {"Laptop", "West"}
    assert top.contribution_pp == pytest.approx(-11.08, abs=0.05)


# ------------------------------------------------- bug 1: casing fragmentation


def test_region_variants_are_merged_before_grouping(sales, march):
    """`West`, `west`, and `" West "` are one segment, not three."""
    assert sales["region"].nunique() == 16  # the raw mess
    region = march.breakdowns["region"]
    assert len(region.slices) == 4

    west = next(s for s in region.slices if s.segment == "West")
    assert west.contribution_pp == pytest.approx(-10.82, abs=0.05)
    assert west.change == pytest.approx(-312_457, abs=1_000)  # not the split -283,234


def test_normalization_is_reported_not_silent(march):
    assert any("region" in note and "merged" in note for note in march.notes)


# ------------------------------------------------ bug 2: reconciliation checks


def test_every_dimension_reconciles_to_the_total(march):
    for name, breakdown in march.breakdowns.items():
        assert breakdown.reconciles, f"{name} residual {breakdown.residual}"
    assert march.intersection.reconciles


def test_the_reconcile_check_can_actually_fail():
    """A check that cannot fail is decoration, not verification."""
    dropped = Breakdown(
        dimension="region",
        slices=[Slice("West", 100.0, 60.0, -40.0, -4.0, -40.0, 10.0)],
        residual=-25.0,  # 25 units unaccounted for
    )
    assert not dropped.reconciles


def test_segments_present_in_only_one_period_are_kept(sales):
    """Index-aligned subtraction drops them, which is how totals silently break."""
    before = pd.Series({"West": 100.0, "East": 50.0})
    after = pd.Series({"West": 80.0, "South": 30.0})  # East gone, South new

    result = _slices(before, after, total_before=150.0)
    segments = {s.segment for s in result}
    assert segments == {"West", "East", "South"}

    # Naive pandas subtraction would silently lose both of the non-overlapping ones.
    assert (after - before).dropna().index.tolist() == ["West"]
    assert sum(s.change for s in result) == pytest.approx(-40.0)


def test_missing_values_become_a_segment_rather_than_being_dropped(march):
    channel = march.breakdowns["channel"]
    assert any(s.segment == "(missing)" for s in channel.slices)
    assert channel.reconciles


# --------------------------------------------- bug 3: overlapping partitions


def test_contributors_are_labelled_with_their_dimension(march):
    """Three partitions of the same money must not be presented as one ranking."""
    labelled = march.top_contributors(4)
    assert all(isinstance(dim, str) and dim in march.breakdowns for dim, _ in labelled)
    assert len({dim for dim, _ in labelled}) > 1  # genuinely different dimensions


def test_each_dimension_independently_partitions_the_total(march):
    for breakdown in march.breakdowns.values():
        assert sum(s.change for s in breakdown.slices) == pytest.approx(march.delta, abs=0.01)


# ----------------------------------------------------- bug 4: the decoy trap


def test_the_decoy_is_flagged(march):
    """South x Docking Station: -61% on its own, but only -0.66pp of the move."""
    decoy = next(
        s for s in march.intersection.slices if set(s.segment.split(" x ")) == {"Docking Station", "South"}
    )
    assert decoy.own_pct_change == pytest.approx(-61.4, abs=1.0)
    assert abs(decoy.contribution_pp) < 1.0
    assert decoy.is_decoy


def test_the_decoy_does_not_outrank_the_real_answer(march):
    ranked = march.intersection.slices
    real = next(i for i, s in enumerate(ranked) if set(s.segment.split(" x ")) == {"Laptop", "West"})
    decoy = next(i for i, s in enumerate(ranked) if set(s.segment.split(" x ")) == {"Docking Station", "South"})
    assert real < decoy


# ------------------------------------------------------------------ behaviour


# ------------------------------------------- direction: rising vs falling


def _two_period_frame(before: dict[str, float], after: dict[str, float]) -> pd.DataFrame:
    rows = [
        {"d": pd.Timestamp("2026-01-15"), "seg": k, "v": v} for k, v in before.items()
    ] + [{"d": pd.Timestamp("2026-02-15"), "seg": k, "v": v} for k, v in after.items()]
    return pd.DataFrame(rows)


def test_leading_contributor_on_a_rising_metric():
    """`slices` is stored ascending, so index 0 is the biggest *counter*-move."""
    frame = _two_period_frame(
        before={"big": 100.0, "small": 10.0, "shrinking": 50.0},
        after={"big": 200.0, "small": 12.0, "shrinking": 40.0},
    )
    analysis = analyze_change(frame, metric="v", date_column="d", dimensions=["seg"])
    assert analysis.direction == 1

    breakdown = analysis.breakdowns["seg"]
    assert breakdown.slices[0].segment == "shrinking"  # the trap
    assert breakdown.leading(analysis.direction).segment == "big"
    assert analysis.headline()[1].segment == "big"


def test_leading_contributor_on_a_falling_metric():
    frame = _two_period_frame(
        before={"big": 200.0, "small": 10.0, "growing": 40.0},
        after={"big": 100.0, "small": 9.0, "growing": 50.0},
    )
    analysis = analyze_change(frame, metric="v", date_column="d", dimensions=["seg"])
    assert analysis.direction == -1
    assert analysis.headline()[1].segment == "big"


def test_ranked_excludes_counter_movers():
    frame = _two_period_frame(
        before={"up": 100.0, "down": 100.0}, after={"up": 200.0, "down": 80.0}
    )
    analysis = analyze_change(frame, metric="v", date_column="d", dimensions=["seg"])
    ranked = analysis.breakdowns["seg"].ranked(analysis.direction)
    assert [s.segment for s in ranked] == ["up"]


def test_decoy_threshold_is_relative_to_the_total_change():
    """An absolute pp threshold flags the wrong slices when the total is large."""
    frame = _two_period_frame(
        before={"main": 1000.0, "tiny": 4.0}, after={"main": 1900.0, "tiny": 40.0}
    )
    analysis = analyze_change(frame, metric="v", date_column="d", dimensions=["seg"])
    slices = {s.segment: s for s in analysis.breakdowns["seg"].slices}

    # `tiny` moved +900% but explains under 4% of the rise, despite being 3.6pp.
    assert slices["tiny"].contribution_pp > 1.0
    assert abs(slices["tiny"].share_of_change) < 0.10
    assert slices["tiny"].is_decoy
    assert not slices["main"].is_decoy


def test_a_diffuse_change_fails_the_concentration_check():
    """No single segment drives it, so attribution should not be claimed."""
    rng = np.random.default_rng(0)
    rows = [
        {
            "d": pd.Timestamp("2026-01-15") if m == 1 else pd.Timestamp("2026-02-15"),
            "seg": f"s{i % 10}",
            "v": (100 if m == 1 else 90) + rng.normal(0, 1),
        }
        for m in (1, 2)
        for i in range(200)
    ]
    analysis = analyze_change(
        pd.DataFrame(rows), metric="v", date_column="d", dimensions=["seg"]
    )
    concentration = next(c for c in analysis.checks if "concentrated" in c.name)
    assert not concentration.passed
    assert "broad" in concentration.detail


def test_requires_two_periods():
    df = pd.DataFrame({"d": [pd.Timestamp("2026-01-01")] * 3, "v": [1.0, 2.0, 3.0]})
    with pytest.raises(ValueError, match="at least two"):
        analyze_change(df, metric="v", date_column="d")


def test_coerce_numeric_handles_currency_percent_and_accounting_negatives():
    series = pd.Series(["$1,234.56", "(500.00)", "12%", "  $7.00 "])
    assert coerce_numeric(series).tolist() == [1234.56, -500.0, 0.12, 7.0]


def test_normalize_reports_what_it_merged():
    series = pd.Series(["West", "west", " West ", "East", "N/A", None])
    normalized, report = normalize_categorical(series)
    assert normalized.tolist() == ["West", "West", "West", "East", "(missing)", "(missing)"]
    assert report.merged == {"West": ["west", " West "]} or set(report.merged) == {"West"}
    assert report.missing_rows == 2
